-- Run this entire file once in Supabase Dashboard > SQL Editor.

create table if not exists public.media_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  title text not null,
  type text not null,
  status text not null,
  rating integer not null default 0 check (rating between 0 and 10),
  poster_url text,
  original_poster_url text,
  crop_data jsonb,
  summary text not null default '',
  review text not null default '',
  notes text not null default '',
  genres jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  date_started date,
  date_completed date,
  platform text not null default 'Other',
  episodes_watched integer,
  total_episodes integer,
  favorite boolean not null default false,
  journal jsonb not null default '[]'::jsonb,
  deleted_at timestamptz,
  last_viewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.custom_options (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  type text not null check (type in ('platform', 'mediaType')),
  name text not null,
  value text not null,
  unique (user_id, type, value)
);

create table if not exists public.entry_versions (
  id bigint generated by default as identity primary key,
  entry_id bigint not null references public.media_entries(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  timestamp timestamptz not null default now(),
  data jsonb not null
);

create index if not exists media_entries_user_id_idx on public.media_entries(user_id);
create index if not exists custom_options_user_id_idx on public.custom_options(user_id);
create index if not exists entry_versions_entry_id_idx on public.entry_versions(entry_id);

create or replace function public.save_media_version()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.entry_versions (entry_id, user_id, data)
  values (new.id, new.user_id, to_jsonb(new));
  return new;
end;
$$;

drop trigger if exists save_media_version_trigger on public.media_entries;
create trigger save_media_version_trigger
after insert or update on public.media_entries
for each row execute function public.save_media_version();

alter table public.media_entries enable row level security;
alter table public.custom_options enable row level security;
alter table public.entry_versions enable row level security;

drop policy if exists "Users manage their media" on public.media_entries;
create policy "Users manage their media" on public.media_entries for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage their options" on public.custom_options;
create policy "Users manage their options" on public.custom_options for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users read their versions" on public.entry_versions;
create policy "Users read their versions" on public.entry_versions for select
using (auth.uid() = user_id);

-- Explicit Data API grants are required when "Automatically expose new tables"
-- is disabled during project creation. RLS policies still enforce row ownership.
grant usage on schema public to anon, authenticated;
grant select on public.media_entries, public.custom_options, public.entry_versions to anon;
grant select, insert, update, delete on public.media_entries, public.custom_options to authenticated;
grant select on public.entry_versions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public)
values ('media-posters', 'media-posters', true)
on conflict (id) do update set public = true;

drop policy if exists "Users upload their posters" on storage.objects;
create policy "Users upload their posters" on storage.objects for insert to authenticated
with check (bucket_id = 'media-posters' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "Users update their posters" on storage.objects;
create policy "Users update their posters" on storage.objects for update to authenticated
using (bucket_id = 'media-posters' and owner_id = auth.uid()::text);

drop policy if exists "Users delete their posters" on storage.objects;
create policy "Users delete their posters" on storage.objects for delete to authenticated
using (bucket_id = 'media-posters' and owner_id = auth.uid()::text);
