-- Preserve separate revisions between editing sessions while consolidating
-- only autosaves generated by the same rapid typing burst.

create or replace function public.save_media_version()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  latest_version public.entry_versions%rowtype;
  significant_change boolean := false;
begin
  if tg_op = 'INSERT' then
    insert into public.entry_versions (entry_id, user_id, data, revision_kind)
    values (new.id, new.user_id, to_jsonb(new), 'initial');
    return new;
  end if;

  if current_setting('aftercredits.restore_in_progress', true) = 'true' then
    return new;
  end if;

  if (to_jsonb(new) - array['updated_at', 'last_viewed_at']) =
     (to_jsonb(old) - array['updated_at', 'last_viewed_at']) then
    return new;
  end if;

  significant_change :=
    old.title is distinct from new.title or
    old.type is distinct from new.type or
    old.status is distinct from new.status or
    old.rating is distinct from new.rating or
    old.platform is distinct from new.platform or
    old.favorite is distinct from new.favorite or
    old.deleted_at is distinct from new.deleted_at;

  select * into latest_version
  from public.entry_versions
  where entry_id = new.id and user_id = new.user_id
  order by timestamp desc
  limit 1;

  if not significant_change
     and latest_version.id is not null
     and latest_version.revision_kind = 'autosave'
     and latest_version.timestamp >= now() - interval '3 seconds' then
    update public.entry_versions
    set data = to_jsonb(new), timestamp = now()
    where id = latest_version.id;
  else
    insert into public.entry_versions (entry_id, user_id, data, revision_kind)
    values (new.id, new.user_id, to_jsonb(new), 'autosave');
  end if;

  return new;
end;
$$;

